site_name: "Starter's Creek"
personality: casual
show_signup: false
social:
  -
    id: o7RuYwqt
    name: Twitter
    url: 'https://twitter.com/statamic'
    icon: twitter
  -
    id: jqNIE9QP
    name: Github
    url: 'https://github.com/statamic/starter-kit-starters-creek'
    icon: github
description: 'An independent publication about design, culture, and the curious business of being alive.'
